# Copyright (c) 2000 by t-ishii66. All rights reserved. -----------------#
# TinyItron First Boot -------------------------------------------------------#
#
# First-stage boot loader (boot sector / MBR), executed in 16-bit real mode.
#
# When a PC powers on, the BIOS performs hardware initialization and then
# reads the first sector (512 bytes) of the boot device (floppy disk in
# this case) into memory at the fixed address 0x0000:0x7C00 (linear 0x7C00).
# The BIOS verifies the boot signature (0xAA55 at offset 510) and jumps
# to 0x7C00 to begin execution.  This file IS that first sector.
#
# Overall boot sequence:
#   boot.s (this) -> start.s -> run.s -> main()
#
# Execution flow:
#   1. BIOS loads us at 0x07C0:0000 (linear 0x7C00).
#   2. Relocate ourselves to 0x7000:0000 (linear 0x70000) so that the
#      memory range 0x2000-0x1FFFF is free for the kernel image.
#      Without relocation, we would sit at 0x7C00 and overlap with
#      the area where we want to load the kernel.
#   3. Print boot banner ("Booting TinyITRON 1.0.0 ...") via BIOS INT 0x10.
#   4. Patch the BIOS floppy disk parameter table (IVT vector 0x1E) to
#      use our custom fd144 table for 1.44 MB geometry.
#   5. Read logical sectors 1..299 from floppy into memory starting at
#      segment 0x0200 (linear 0x2000), with a spinning progress indicator.
#      When the 16-bit offset wraps at 64 KB, the segment register is
#      advanced by 0x1000 to continue loading into the next 64 KB region.
#   6. Print "Second Boot ..." and far jump to 0x0300:0000 (linear 0x3000)
#      to enter the second-stage boot loader (start.s).
#
# The loaded image at 0x2000 is actually three files concatenated by
# the Makefile with `cat boot/boot table start kernel > i386`:
#
#   0x2000 (sector 1):  table  -- GDT (4096 bytes, padded by .org 4096)
#   0x3000 (sector 9):  start  -- 16-to-32-bit transition (1024 bytes, .org 1024)
#   0x3400 (sector 11): kernel -- 32-bit kernel (linked at -Ttext=0x3400)
#
# Floppy geometry assumed: 1.44 MB, 80 cylinders, 2 heads, 18 sectors/track.
# Total capacity: 80 * 2 * 18 * 512 = 1,474,560 bytes = 1.44 MB.
#
# Memory map after loading completes:
#   0x00000 - 0x003FF  IVT (Interrupt Vector Table, 256 entries * 4 bytes)
#   0x00400 - 0x004FF  BIOS Data Area (BDA)
#   0x02000 - 0x02FFF  GDT table (loaded from 'table', generated by genasm.c)
#   0x03000 - 0x033FF  start.s (second-stage boot loader, 16-bit real mode)
#   0x03400 - ~0x1DFFF Kernel image (32-bit protected mode code)
#   0x07C00 - 0x07DFF  Original boot sector (no longer used after relocation)
#   0x70000 - 0x701FF  Relocated boot sector (this code, segment 0x7000)
#
# Calling convention used in this file:
#   All functions use 16-bit near calls within segment m_base (0x7000).
#   Arguments are passed on the stack (cdecl-like).
#   The caller is responsible for cleaning up the stack after the call.
#
# 16 bit real mode -----------------------------------------------------------#

# segment environment --------------------------------------------------------#
# These are SEGMENT values, not linear addresses.
# In real mode, physical (linear) address = segment * 16 + offset.
# For example: segment 0x07C0, offset 0 -> linear 0x07C0 * 16 + 0 = 0x7C00.
.equ b_base, 0x07c0		# Boot sector segment:   0x07C0 * 16 = linear 0x7C00
.equ m_base, 0x7000		# Relocation segment:    0x7000 * 16 = linear 0x70000
.equ kt_base, 0x0200		# Kernel load segment:   0x0200 * 16 = linear 0x2000
.equ s_base, 0x0300		# start.s entry segment: 0x0300 * 16 = linear 0x3000
.equ delta_seg, 0x1000		# Segment advance on 64 KB wrap: 0x1000 * 16 = 0x10000

.code16				# Generate 16-bit x86 code (real mode)
.text
.globl start
		.org	0	# Binary starts at offset 0 (no ELF headers,
				# linked with --oformat binary -Ttext 0x0)

# ===========================================================================
# start -- Entry point
# ===========================================================================
# BIOS has just loaded this 512-byte sector at 0x07C0:0000 (linear 0x7C00)
# and jumped here.  DL contains the boot drive number (0 = floppy A:).
#
# We need to relocate ourselves out of the way because the kernel image
# will be loaded starting at linear 0x2000, and the boot sector at 0x7C00
# would be in the middle of the loaded data (0x2000 to ~0x1E000).
# By copying to 0x70000, we are safely above the kernel load area.
start:
		movw	$b_base, %ax
		movw	%ax, %ds	# DS = 0x07C0 (points to our data in original location)
		movw	%ax, %ss	# SS = 0x07C0 (stack in same segment)
		movw	$1024, %sp	# SP = 1024; stack top at 0x07C0:0400 = linear 0x8000
					# Stack grows downward from here.  1024 bytes is
					# plenty for the few nested calls we make.

		# --- Step 1: Relocate 512 bytes from 0x07C0:0 to 0x7000:0 ---
		# Source:      DS:SI = 0x07C0:0000 (linear 0x7C00)
		# Destination: ES:DI = 0x7000:0000 (linear 0x70000)
		movw	$m_base, %ax
		movw	%ax, %es	# ES = 0x7000 (destination segment)
		movw	$0, %di		# DI = 0 (destination offset)
		movw	$start, %si	# SI = 0 (source offset; 'start' = 0 due to .org 0)
		movw	$512, %cx	# CX = 512 (byte count = one full sector)
		rep	movsb		# Copy DS:SI -> ES:DI, decrement CX, repeat

		# --- Step 2: Far jump to the relocated copy ---
		# This updates CS to m_base (0x7000) so we execute from the new
		# location.  Without this, CS still points to 0x07C0 and we would
		# be executing from the original (soon-to-be-overwritten) location.
		ljmp	$m_base, $jumphere

jumphere:
		# --- Step 3: Re-initialize all segment registers ---
		# Now executing from 0x7000:xxxx (linear 0x70000+).
		# DS, ES, SS must all point to m_base so that data references
		# (message strings, variables like 'dot') resolve correctly.
		movw	$m_base, %ax
		movw	%ax, %ds	# DS = 0x7000
		movw	%ax, %es	# ES = 0x7000 (will be changed by load)
		movw	%ax, %ss	# SS = 0x7000
		movw	$1024, %sp	# Re-establish stack in new segment

		# --- Step 4: Print boot banner ---
		# Display "Booting TinyITRON 1.0.0 Copyright ..." using BIOS INT 0x10.
		# The puts function expects a string pointer on the stack.
		movw	$message, %bx
		pushw	%bx		# Push pointer to message string
		call	puts		# Print it
		popw	%bx		# Clean up stack (caller cleans)

		# --- Step 5: Patch floppy disk parameters ---
		# Replace the BIOS default floppy parameter table with our fd144
		# table, which has correct parameters for a 1.44 MB 3.5" drive.
		call	init_fd

		# --- Step 6: Load kernel image from floppy ---
		# Read sectors 1..229 into memory starting at segment 0x0200 (linear 0x2000).
		# This loads the GDT table, start.s, and the kernel into contiguous memory.
		call	load

		# --- Step 7: Jump to second-stage boot loader ---
		# Print "Second Boot ..." and hand off control to start.s.
		movw	$secondboot, %bx
		pushw	%bx
		call	puts
		popw	%bx
		ljmp	$s_base, $0	# Far jump to 0x0300:0000 (linear 0x3000 = start.s)
					# start.s will enable A20, load GDT/IDT,
					# switch to protected mode, and jump to the kernel.

		# Should never reach here.  Infinite loop as safety net.
loop0:
		jmp	loop0

# ===========================================================================
# puts -- Print a null-terminated string
# ===========================================================================
# Uses BIOS teletype output (INT 0x10, AH=0x0E) to print each character.
#
# Calling convention:
#   push  $string_ptr    ; pointer to null-terminated string (within DS segment)
#   call  puts
#   pop   %bx            ; caller cleans stack
#
# Stack frame:
#   4(%bp) = string pointer (first and only argument)
#   2(%bp) = return address (pushed by call)
#   0(%bp) = saved BP
puts:
		pushw	%bp
		movw	%sp, %bp
		pushw	%bx		# Save callee-saved registers
		pushw	%cx

		movw	4(%bp), %bx	# BX = pointer to null-terminated string
puts_1:
		movb	(%bx), %al	# AL = next character from string
		cmpb	$0x00, %al	# Is it the null terminator?
		je	puts_2		# Yes -> we're done
		call	putc		# No -> print this character
		incw	%bx		# Advance to next character
		jmp	puts_1		# Loop
puts_2:
		popw	%cx		# Restore callee-saved registers
		popw	%bx
		popw	%bp
		ret

# ===========================================================================
# putc -- Print a single character
# ===========================================================================
# Prints the character in AL using BIOS INT 0x10, function 0x0E (teletype).
# This function writes one character at the current cursor position and
# advances the cursor.  Special characters (CR, LF, BS) are handled by BIOS.
#
# Input:  AL = character to print
# Output: cursor is advanced
putc:
		pushw	%bx
		movb	$0x0e, %ah	# AH = 0x0E: BIOS teletype output function
		movb	$2, %bl		# BL = color attribute (2 = green foreground)
					# Note: BL is only used in graphics mode, but
					# setting it doesn't hurt in text mode.
		int	$0x10		# BIOS video services interrupt
		popw	%bx
		ret

# ===========================================================================
# load -- Read kernel image from floppy disk
# ===========================================================================
# Reads logical sectors 1 through 229 from the floppy disk into memory
# starting at segment kt_base (0x0200, linear 0x2000).
#
# Total data loaded: 229 sectors * 512 bytes/sector = 117,248 bytes (~114 KB)
#
# Sector 0 is the boot sector itself (this code), so we skip it and start
# from sector 1.  The loaded data contains:
#   Sectors  1-8   -> table (GDT, 4096 bytes)  -> linear 0x2000
#   Sectors  9-10  -> start.s (1024 bytes)      -> linear 0x3000
#   Sectors 11-229 -> kernel (~112 KB)          -> linear 0x3400
#
# The 16-bit offset register (BX) can only address 64 KB within a segment.
# After 128 sectors (128 * 512 = 65536 = 64 KB), BX wraps around to 0.
# When this happens, we advance ES by delta_seg (0x1000 segments = 64 KB)
# so that ES:BX continues to point to the next byte of memory.
load:
		movw	$kt_base, %ax
		movw	%ax, %es	# ES = 0x0200 (initial destination segment)
		movw	$0x1, %ax	# AX = 1 (first logical sector to read)
		movw	$0x0000, %bx	# BX = 0 (offset within segment)
load_1:
		# Save BX (offset) and AX (sector number) across the call to readsect,
		# because readsect uses these registers for BIOS INT 0x13.
		pushw	%bx
		pushw	%ax
		call	readsect	# Read one sector: logical sector AX -> ES:BX
		popw	%ax		# Restore sector number
		popw	%bx		# Restore offset
		addw	$512, %bx	# Advance destination offset by one sector
		incw	%ax		# Next logical sector number

# segment rotation check -----------------------------------------------------#
# The 16-bit BX register wraps from 0xFFFF+1 to 0x0000 after 128 sectors.
# testw $0xffff, %bx tests all bits of BX -- the zero flag is set only when
# BX is exactly 0 (i.e., it just wrapped around).
		testw	$0xffff, %bx	# Did BX wrap to 0?
		jnz	over_1		# No -> continue normally
		# Yes -> BX wrapped.  Advance ES by delta_seg to access next 64 KB.
		pushw	%ax		# Save sector number
		movw	%es, %ax
		addw	$delta_seg, %ax	# ES += 0x1000 (64 KB in linear address)
		movw	%ax, %es
		popw	%ax		# Restore sector number
over_1:

# load count -----------------------------------------------------------------#
# We load sectors 1 through 299.  When AX reaches 300, all sectors are loaded.
# (299 sectors = 153,088 bytes: table + start + kernel, loaded at 0x2000)
		cmpw	$300, %ax	# Have we read all 299 sectors?
		je	load_2		# Yes -> done

		jmp	load_1		# No -> read next sector
load_2:
		ret

# ===========================================================================
# readsect -- Read one sector from floppy disk
# ===========================================================================
# Reads a single sector using BIOS INT 0x13, function 02h (read sectors).
#
# Arguments:
#   4(%bp) = logical sector number (0-based; 0 = boot sector, 1 = first data sector)
#   ES:BX  = destination buffer (set by caller in the 'load' function)
#
# The function converts the logical sector number to CHS (Cylinder, Head, Sector)
# addressing, which is what the BIOS disk service requires.
#
# CHS conversion for 1.44 MB floppy (18 sectors/track, 2 heads, 80 cylinders):
#
#   sectors_per_cylinder = 18 (sectors/track) * 2 (heads) = 36
#
#   cylinder = logical_sector / 36
#   remainder = logical_sector % 36
#   head     = remainder / 18
#   sector   = (remainder % 18) + 1    (BIOS uses 1-based sector numbers)
#
# Example: logical sector 37
#   37 / 36 = 1 remainder 1  -> cylinder = 1
#   1 / 18  = 0 remainder 1  -> head = 0, sector = 1 + 1 = 2
#   So: CHS = (1, 0, 2)
#
# Note: The 8-bit divb instruction limits cylinder numbers to 0-255.
# Since we only read up to sector 229 (cylinder 6), this is not a problem.
# The original comment warned about ignoring top 2 bits of cylinder, which
# refers to the CH register only holding 8 bits of the 10-bit cylinder field
# in the INT 0x13 interface.  Again, not an issue for our small image.
readsect:
		pushw	%bp
		movw	%sp, %bp

		# --- CHS conversion ---
		movw	4(%bp), %ax	# AX = logical sector number (argument)
		movb	$36, %dl	# DL = 36 = sectors per cylinder (18 spt * 2 heads)
		divb	%dl		# Unsigned divide AX by DL:
					#   AL = quotient  = cylinder number
					#   AH = remainder = (head * 18) + sector_0based
		movb	%al, %ch	# CH = cylinder number (for INT 0x13)
		movb	%ah, %al	# Move remainder to AL for second division
		movb	$0, %ah		# Clear AH (prepare AX = remainder as 16-bit value)

		movb	$18, %dl	# DL = 18 = sectors per track
		divb	%dl		# Unsigned divide AX by DL:
					#   AL = quotient  = head number (0 or 1)
					#   AH = remainder = sector number (0-based)
		movb	%al, %dh	# DH = head number (for INT 0x13)
		movb	%ah, %cl	# CL = sector number (still 0-based)

		incb	%cl		# Convert to 1-based (BIOS expects sectors 1..18)

		# --- Issue BIOS disk read ---
		# INT 0x13, AH=02h: Read Sectors
		#   AL = number of sectors to read (1)
		#   CH = cylinder number (low 8 bits)
		#   CL = sector number (1-based, bits 0-5)
		#   DH = head number
		#   DL = drive number (0 = first floppy drive A:)
		#   ES:BX = destination buffer address
		# Returns:
		#   CF = 0 on success, 1 on error
		#   AH = status code (0 = success)
		movb	$0, %dl		# DL = 0 (drive A:)
		movb	$2, %ah		# AH = 02h (read sectors function)
		movb	$1, %al		# AL = 1 (read one sector at a time)
		int	$0x13		# Call BIOS disk services; CF set on error

# --- Spinning progress indicator ---
# While loading, display a spinning animation to show progress.
# The spinner cycles through 4 frames: - \ | /
# The output string is dot0 = "\b" + frame_char + "\0".
# The backspace (0x08) moves the cursor back one position, then the new
# frame character overwrites the previous one, creating the animation effect.
# The frame advances every 4 sectors (shrw $2 = divide by 4) to avoid
# spinning too fast.
		movw	dot, %ax	# AX = tick counter (incremented per sector)
		incw	%ax		# Increment tick
		movw	%ax, dot	# Store back

		shrw	$2, %ax		# Divide by 4: advance frame every 4 ticks
		andw	$0x0003, %ax	# AX = tick_count mod 4 (index 0..3)
		movw	$dot_data, %bx	# BX = address of frame table "-\|/"
		addw	%ax, %bx	# BX = &dot_data[index]
		movb	(%bx), %al	# AL = frame character for this tick
		movb	%al, dot1	# Patch the character into the output string

		movw	$dot0, %bx	# BX -> "\b<char>\0" (spinner output string)

		jnc	readsect_1	# CF clear (no error) -> show spinner
		movw	$readerr, %bx	# CF set (error) -> show "Read Sector Error"
readsect_1:
		pushw	%bx		# Push string pointer for puts
		call	puts		# Print spinner or error message
		popw	%bx		# Clean up stack

		popw	%bp
		ret

# ===========================================================================
# init_fd -- Initialize floppy disk parameters
# ===========================================================================
# The BIOS maintains a pointer to the floppy disk parameter table at
# IVT vector 0x1E.  This is a far pointer (segment:offset) stored at
# linear address 0x0000:0x0078 (vector 0x1E * 4 = 0x78).
#
# We replace this pointer with the address of our own fd144 table, which
# contains parameters suitable for a 1.44 MB 3.5" floppy disk.
# The BIOS INT 0x13 reads these parameters to configure the floppy
# disk controller (FDC) timing, sector count, gap lengths, etc.
init_fd:
		pushw	%es		# Save ES (currently m_base, needed later)
		movw	$0x78, %bx	# BX = 0x78 = offset of IVT entry for vector 0x1E
		movw	$0, %ax
		movw	%ax, %es	# ES = 0x0000 (IVT is at the very start of memory)
		movw	$fd144, %es:(%bx)	# IVT[0x1E].offset = offset of fd144
		movw	%ds, %es:2(%bx)		# IVT[0x1E].segment = DS (= m_base = 0x7000)
						# So the far pointer now points to 0x7000:fd144
						# which is our custom parameter table.
		popw	%es
		ret

# ===========================================================================
# fd144 -- Floppy disk parameter table for 1.44 MB 3.5" drive
# ===========================================================================
# This is an 11-byte table that the BIOS/FDC uses for disk I/O timing.
# The format follows the IBM PC/AT specification:
#
#   Byte  Value  Meaning
#   ----  -----  -------
#    0    0xAF   SRT (step rate time) = 0xA (6ms), HUT (head unload time) = 0xF
#    1    0x02   HLT (head load time) = 1 (2ms), DMA mode = 1 (DMA enabled)
#    2    25     Motor off delay (in 55ms ticks; 25 * 55ms = 1.375 sec)
#    3    2      Bytes per sector code: 2 = 512 bytes/sector
#    4    36     End of track (sectors per cylinder = 18 spt * 2 heads)
#    5    0x1B   Gap length for read/write operations (27 bytes)
#    6    0xFF   Data length (ignored when bytes/sector != 0)
#    7    0x54   Gap length for format operations (84 bytes)
#    8    0xF6   Format fill byte (sectors filled with 0xF6 during format)
#    9    15     Head settle time (15 ms)
#   10    8      Motor start time (8 * 125ms = 1 second)
fd144:		.byte	0xaf, 2, 25, 2, 36, 0x1b, 0xff, 0x54, 0xf6, 15, 8

# ===========================================================================
# Message strings
# ===========================================================================

# Printed just before jumping to start.s (the second-stage boot loader).
# 0x0A = Line Feed, 0x0D = Carriage Return, 0x00 = null terminator.
secondboot:	.byte	0x0a, 0x0d
		.ascii	"Second Boot ..."
		.byte   0x0a, 0x0d, 0x00

# Boot banner displayed immediately after relocation.
message:
		.ascii	"Booting TinyITRON 1.0.0 "
		.ascii	"Copyright (c) 2000-2026 by t-ishii66"
		.byte   0x0a, 0x0d, 0x00

# Error message displayed when INT 0x13 returns with CF=1 (read failure).
readerr:	.ascii	"Read Sector Error"
		.byte	0x0a, 0x0d, 0x00

# ===========================================================================
# Spinner animation data
# ===========================================================================
# The spinner output string is 3 bytes: backspace + frame_char + null.
# readsect patches dot1 with the current frame character on each sector read.
# When puts prints this string, the backspace moves the cursor back and the
# frame character overwrites the previous one, creating the spinning effect.
dot0:		.byte	0x08		# 0x08 = backspace (BS) -- move cursor left
dot1:		.ascii	"-"		# Current animation frame (patched at runtime)
		.byte	0x00		# Null terminator

# The four animation frames, indexed by (tick_count / 4) % 4:
dot_data:	.ascii	"-\\|/"		# Frame 0: -   Frame 1: \   Frame 2: |   Frame 3: /
		.byte	0x00		# (null terminator, not used by index but harmless)

# Tick counter: incremented once per sector read.
dot:		.word	0x0000

# ===========================================================================
# Boot signature
# ===========================================================================
# The BIOS requires the last two bytes of the boot sector (offset 510-511)
# to contain the magic number 0xAA55.  Without this signature, the BIOS
# will not recognize this sector as bootable and will report "No boot device".
#
# .org 510 pads everything up to byte 510 with zeros.  If the actual code
# and data above exceed 510 bytes, the assembler will report an error.
# This enforces that the boot sector is exactly 512 bytes.
		.org	510
		.word	0xaa55
