# Copyright (c) 2000 by t-ishii66. All rights reserved. -----------------#
# second boot loader (Real Mode) 16 bit to 32 bit ----------------------------#
#
# =============================================================================
# start.s -- Second-Stage Boot Loader (Real Mode -> Protected Mode)
# =============================================================================
#
# This file implements the second-stage boot loader for the tiny-itron RTOS.
# It is loaded by the first-stage boot loader (boot.s) from the floppy image
# into memory at segment 0x0300 (linear address 0x3000).
#
# Execution flow:
#   1. Set up real-mode segment registers and stack
#   2. Enable the A20 address line (to access memory above 1 MB)
#   3. Load the IDT and GDT descriptor tables (GDT was built by genasm.c)
#   4. Switch the CPU from 16-bit real mode to 32-bit protected mode
#   5. Flush the prefetch queue with a far jump through a 16-bit code segment
#   6. Set up protected-mode data/stack segment registers
#   7. Far jump to the 32-bit kernel entry point (run.s) at linear 0x3400
#
# Memory layout at this stage:
#   0x0000 - 0x1FFF : Real-mode IVT, BIOS data, free low memory
#   0x2000 - 0x20FF : GDT (256 bytes, generated by genasm.c)
#   0x2100 - 0x28FF : IDT (2048 bytes, generated by genasm.c)
#   0x3000 - 0x33FF : This file (start.s, padded to exactly 1024 bytes)
#   0x3400+         : Kernel code (run.s, then the rest of the kernel)
#
# The floppy image is built by concatenating: boot.bin + start.bin + kernel.
# The .org 1024 directive at the end pads this file to exactly 1024 bytes
# so that the kernel binary starts at a known offset.
#
# GDT selectors used here (defined by genasm.c):
#   0x08 = 16-bit kernel code segment (base=0x3000, limit=0xFFFF)
#          Used for the initial far jump after entering protected mode.
#          This segment has base=0x3000 so code addresses are relative to
#          where start.s is loaded, making the flush_start label work.
#   0x10 = 16-bit data segment (base=0xB8000, limit=0xFFFF)
#          Points to VGA text memory; used as DS/ES after mode switch.
#   0x18 = 16-bit stack segment
#   0x20 = 32-bit kernel code segment (base=0, flat model)
#          The final far jump uses this to enter the 32-bit kernel.
#
# Note on far jumps: The two far jumps in this file are manually encoded
# as raw bytes (.byte 0xea + .word offset + .word selector) because the
# GNU assembler in 16-bit mode cannot reliably encode far jumps that cross
# between 16-bit and 32-bit code segments.
#
# This code is also re-executed by the AP (CPU 1) during SMP startup.
# The BSP sends a SIPI with vector=0x03, which directs the AP to begin
# execution at physical address 0x3000 (= 0x03 * 0x1000), i.e., this code.
# Both CPUs follow the same path through protected mode setup, then diverge
# in run.s based on the cpu_num variable.
# =============================================================================

# environment ----------------------------------------------------------------#
# Constants for memory addresses used during boot.
.equ b_base, 0x07c0		# (unused) boot sector segment
.equ s_base, 0x0300		# start.s segment:  0x0300 * 16 = linear 0x3000
.equ k_base, 0x3400		# kernel entry point (linear address, used in pmode)
.equ ks_base, 0x2000		# (unused) GDT base linear address

.code16				# Generate 16-bit real-mode instructions
.text
.globl start
# start ----------------------------------------------------------------------#
# 0x0200:0x1000 --------------------------------------------------------------#
		.org	0x0		# Start at offset 0 within this module
# auto generated code --------------------------------------------------------#
start:

# --- Step 1: Initialize real-mode segment registers and stack ---------------#
# Set DS and ES to s_base (0x0300), so data accesses are relative to
# linear address 0x3000 (where this code is loaded).
		movw	$s_base, %ax
		movw	%ax, %ds
		movw	%ax, %es

# Set up a temporary real-mode stack at SS:SP = 0x1000:0x0400.
# Linear stack address = 0x1000 * 16 + 1024 = 0x10400, growing downward.
# This stack is only used briefly during the A20/GDT/IDT setup below.
		movw	$0x1000, %ax
		movw	%ax, %ss
		movw	$1024, %sp

# --- Step 2: Disable interrupts and prepare for protected mode --------------#
# Disable hardware interrupts. They must remain off until the kernel
# sets up its own IDT handlers and re-enables them via the first task's
# EFLAGS (IF=1) loaded by the TSS hardware task switch.
		cli

# --- Step 3: Enable the A20 address line ------------------------------------#
# On IBM PC compatibles, address line A20 is initially gated off for
# 8086 compatibility, which means addresses wrap around at 1 MB.
# We must enable A20 to access the full 32-bit address space.
# This is done via the keyboard controller (port 0x64/0x60).
		call	a20_init

# --- Step 4: Load the IDT and GDT ------------------------------------------#
# Load the Interrupt Descriptor Table Register (IDTR) and Global Descriptor
# Table Register (GDTR). The actual GDT and IDT data structures live at
# linear addresses 0x2000 and 0x2100 respectively, and were generated by
# genasm.c and written there by the kernel image layout.
# The descriptor pointers (idt_ptr, gdt_ptr) are defined at the bottom
# of this file with the base addresses and limits.
		lidt	idt_ptr
		lgdt	gdt_ptr

# --- Step 5: Switch to protected mode --------------------------------------#
# Set the PE (Protection Enable) bit (bit 0) in CR0.
# After this instruction, the CPU is in protected mode, but the CS register
# still contains a real-mode value. A far jump is needed to load CS with
# a valid protected-mode selector and flush the instruction prefetch queue.
# end of real mode -----------------------------------------------------------#
		movl	%cr0, %eax
		orl	$0x00000001, %eax	# Set PE bit (bit 0)
		movl	%eax, %cr0

# --- Step 6: Far jump to flush prefetch queue and load CS -------------------#
# This is a far jump (opcode 0xEA) to flush_start with selector 0x08.
# Selector 0x08 is a 16-bit code segment with base=0x3000 in the GDT,
# so flush_start is interpreted as an offset from 0x3000.
# This jump serializes the CPU: it flushes the prefetch queue and loads
# CS with the protected-mode selector, completing the mode switch.
# Manually encoded because gas in .code16 mode cannot reliably assemble
# a far jump to a protected-mode segment.
# start protect mode ---------------------------------------------------------#
		.byte	0xea		# Far jump opcode
		.word	flush_start	# Offset within the 0x08 segment
		.word	0x08		# Selector: 16-bit code segment (base=0x3000)
flush_start:

# --- Step 7: Load protected-mode data and stack segment registers -----------#
# Now running in protected mode with CS=0x08 (16-bit code segment).
# Load DS and ES with selector 0x10 (16-bit data segment, base=0xB8000,
# which points to VGA text-mode video memory).
# Load SS with selector 0x18 (16-bit stack segment).
		movw	$0x10, %ax
		movw	%ax, %ds
		movw	%ax, %es
		movw	$0x18, %ax
		movw	%ax, %ss

# --- Step 8: Far jump to the 32-bit kernel entry point ----------------------#
# This far jump transfers control to the kernel (run.s) at linear address
# 0x3400 using selector 0x20 (32-bit flat code segment, base=0).
# Since selector 0x20 has base=0, the offset 0x3400 corresponds directly
# to linear address 0x3400, which is where the kernel is loaded.
# From this point on, the CPU executes 32-bit code and never returns here.
# Manually encoded for the same reason as the previous far jump.
# jump to 32-bit kernel entry point ------------------------------------------#
		.byte	0xea		# Far jump opcode
		.word	k_base		# offset 0x3400 (= -Ttext in Makefile)
		.word	0x20		# selector SEL_K32_C

# --- Infinite loop (should never be reached) --------------------------------#
# Safety net in case the far jump somehow fails. Halts the CPU in a
# tight loop.
# no return ------------------------------------------------------------------#
loop0:
		jmp	loop0

# =============================================================================
# a20_init -- Enable the A20 address line via the keyboard controller (8042)
# =============================================================================
# The 8042 keyboard controller has a secondary function: it controls the
# A20 gate. To enable A20, we send command 0xD1 ("Write Output Port") to
# the command port (0x64), then write 0xDF to the data port (0x60).
# Bit 1 of the output port controls A20: setting it high enables A20.
# 0xDF = 1101_1111 = A20 enabled, keyboard enabled, other bits set.
#
# We must wait for the keyboard controller input buffer to be empty
# before sending each byte, which is what a20_init_wait does.
# a20_init -------------------------------------------------------------------#
a20_init:
		call	a20_init_wait		# Wait for controller to be ready
		movb	$0xd1, %al		# Command: write to output port
		movw	$0x64, %dx		# Keyboard controller command port
		outb	%al, %dx		# Send command
		call	a20_init_wait		# Wait for controller to be ready
		movb	$0xdf, %al		# Data: enable A20 (bit 1 = 1)
		movw	$0x60, %dx		# Keyboard controller data port
		outb	%al, %dx		# Send data byte
		call	a20_init_wait		# Wait for command to complete
		ret

# =============================================================================
# a20_init_wait -- Wait for the 8042 keyboard controller input buffer to empty
# =============================================================================
# Polls the keyboard controller status register (port 0x64).
# Bit 1 of the status register is the "input buffer full" flag.
# We spin until this bit is clear, meaning the controller is ready
# to accept a new command or data byte.
# a20_init_wait --------------------------------------------------------------#
a20_init_wait:
		movw	$0x64, %dx		# Keyboard controller status port
		inb	%dx, %al		# Read status register
		andb	$0x02, %al		# Test bit 1 (input buffer full?)
		jnz	a20_init_wait		# If set, keep polling
		ret				# Controller is ready

# =============================================================================
# hello -- Debug helper: print '9' to the screen via BIOS INT 10h
# =============================================================================
# Uses BIOS video service INT 10h, function 0x0E (teletype output).
# Prints the character '9' (ASCII 0x39) in green (attribute 2).
# This is a diagnostic routine that can be called during real-mode
# execution to verify that the boot loader reached a particular point.
# Only works before protected mode is entered (BIOS interrupts are
# unavailable in protected mode).
# for debug ------------------------------------------------------------------#
hello:
		movb	$0x0e, %ah		# BIOS function: teletype output
		movb	$0x39, %al		# Character to print: '9'
		movb	$2, %bl			# Foreground color: green
		int	$0x10			# Call BIOS video interrupt
		ret

# =============================================================================
# error -- Infinite loop for unrecoverable errors (debug only)
# =============================================================================
error:
		jmp	error

# =============================================================================
# GDT and IDT pseudo-descriptors
# =============================================================================
# These 6-byte structures are loaded by LGDT and LIDT instructions.
# Format: 2-byte limit (size - 1), followed by 4-byte linear base address.
#
# gdt_ptr: GDT is 256 bytes (32 entries x 8 bytes) at linear address 0x2000
# idt_ptr: IDT is 2048 bytes (256 entries x 8 bytes) at linear address 0x2100
#
# Both tables are generated by genasm.c and placed at these fixed addresses
# in the kernel image.

.align	4
gdt_ptr:	.word	256-1		# GDT limit: 255 bytes (256 - 1)
		.word	0x2000, 0x0	# GDT base: linear address 0x00002000

.align	4
idt_ptr:	.word	2047		# IDT limit: 2047 bytes (2048 - 1)
		.word	0x2100		# IDT base: linear address 0x00002100
		.word	0x0

# =============================================================================
# Pad to exactly 1024 bytes
# =============================================================================
# The floppy image is built by concatenating: boot.bin (512 bytes) +
# start.bin (1024 bytes) + kernel binary. The kernel linker script uses
# -Ttext 0x3400, which assumes start.bin is exactly 1024 bytes (0x400).
# If this file were smaller, the kernel code would not start at the
# expected address, and the far jump to k_base (0x3400) would fail.
		.org	1024
